package org.kagelabs.weather;

/**
 * Created by nd on 9/20/15.
 */
public enum Weather {
    SUNNY, RAINY, STORMY, CLOUDY, HOT, COLD, DRY, WET, WINDY,
    HURRICANES, TYPHOONS, SANDSTORMS,SNOWSTORMS, TORNADOS,
    HUMID, FOGGY, SNOW, THUNDERSNOW, HAIL, SLEET, DROUGHT,
    WILDFIRE, BLIZZARD, AVALANCHE, MIST, UNKNOWN;

}
